# Generated by Django 5.1.6 on 2025-03-27 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashbordEtudient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, default='images/image-profil.png', null=True, upload_to='profile_images/'),
        ),
    ]
