# Generated by Django 5.1.6 on 2025-03-27 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashbordEtudient', '0003_alter_userprofile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, default='static/images/profil.png', null=True, upload_to='profile_images/'),
        ),
    ]
