# Generated by Django 5.1.6 on 2025-03-29 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='utilisateur',
            old_name='confirm_mot_de_passe',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='utilisateur',
            old_name='nom',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='mot_de_passe',
        ),
    ]
