# Generated by Django 5.1.7 on 2025-03-26 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, default='static/images/inejihimage.jpeg ', null=True, upload_to='profile_images/'),
        ),
    ]
